# Project information
site_name: 'OMIM Dokumentation'
site_description: 'Virtuelle Ausstellungen der Deutschen Digitalen Bibliothek'
site_author: 'Viktor Grandgeorg <viktor@grandgeorg.de>'

# Copyright
copyright: 'Copyright &copy; 2017 Viktor Grandgeorg, Grandgeorg Websolutions'

# Structure
nav:
    - Einleitung: index.md
    - Anforderungen: install.md
    - Redaktionsserver: dev-srv.md
    - Ausspielungsserver: prod-srv.md
    - Aktualisierungen: updates.md
    - Konfiguration: config.md
    # - Cheatsheet: cheatsheet.md

# Theme
theme:
  name: readthedocs
  custom_dir: themes/readthedocs_ddb
  highlightjs: False

# Options
# extra:
  # logo: 'img/logo.svg'

extra_css:
    - css/extra.css

extra_javascript:
    - js/jquery-3.1.1.min.js
    - js/extra.js

use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  # - codehilite:
  #     guess_lang: false
  #     linenums: false
  - footnotes
  - meta
  - toc:
      permalink: True
  - sane_lists
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - figureAltCaption
